//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiTabla
    {
        public int I1 { get; set; }
        public string C1 { get; set; }
    }
}
